name = "SelfWebsite"
description = "Jacky's personal website"
license = "MIT"
homepage = "https://jacky.refitor.com"
demo = "https://jacky.refitor.com"
min_version = "0.4.0"

generate_feed = true

[extra]

nav = [
  { name = "Blog", path = "/blog/" },
  { name = "Self", path = "/self" },
  { name = "Product", path = "https://jacky.refitor.com" },
  { name = "Github", path = "https://github.com/refitor" }
]

blog_path = "blog"

icon = "icon.png"
profile_small = "icon.png"
profile_large = "profile.jpg"

accent = "#05a081"
accent_light = "#82d0c0"

not_found_message = """
This is not the page you're looking for... return back to [safety?](/)
"""

[author]
name = "Jacky"
homepage = "https://jacky.refitor.com"
